import { execSync } from 'node:child_process';
import { existsSync, unlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

function findSystemBrowser(): string | null {
	const platform = process.platform;

	if (platform === 'darwin') {
		const macPaths = [
			'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
			'/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
			'/Applications/Chromium.app/Contents/MacOS/Chromium',
			'/Applications/Firefox.app/Contents/MacOS/firefox',
		];
		for (const p of macPaths) {
			if (existsSync(p)) return p;
		}
	} else if (platform === 'win32') {
		const winPaths = [
			'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
			'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
			'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
			'C:\\Program Files\\Mozilla Firefox\\firefox.exe',
		];
		for (const p of winPaths) {
			if (existsSync(p)) return p;
		}
	} else {
		// Linux
		const linuxCmds = [
			'google-chrome',
			'google-chrome-stable',
			'chromium-browser',
			'chromium',
			'firefox',
			'firefox-esr',
		];
		for (const cmd of linuxCmds) {
			try {
				execSync(`which ${cmd}`, { stdio: 'ignore' });
				return cmd;
			} catch {
				// ignore and try next
			}
		}
	}

	return null;
}

export async function compressPngToWebp(pngPath: string, webpPath: string, quality: number = 75): Promise<boolean> {
	// 1. Try macOS native sips
	if (process.platform === 'darwin') {
		try {
			execSync(`sips -s format webp "${pngPath}" --out "${webpPath}"`, { stdio: 'ignore' });
			if (existsSync(webpPath)) {
				return true;
			}
		} catch (err) {
			// fallback
		}
	}

	// 2. Try Python PIL/Pillow
	try {
		execSync(
			`python3 -c "from PIL import Image; im = Image.open('${pngPath}'); im.save('${webpPath}', 'WEBP', quality=${quality})"`,
			{ stdio: 'ignore' },
		);
		if (existsSync(webpPath)) {
			return true;
		}
	} catch (err) {
		// fallback
	}

	// 3. Try cwebp command line utility
	try {
		execSync(`cwebp -q ${quality} "${pngPath}" -o "${webpPath}"`, { stdio: 'ignore' });
		if (existsSync(webpPath)) {
			return true;
		}
	} catch (err) {
		// fallback
	}

	return false;
}

export async function captureWebsiteScreenshot(url: string, destWebpPath: string): Promise<void> {
	let target = url.trim();
	if (!target.startsWith('http://') && !target.startsWith('https://')) {
		target = `https://${target}`;
	}

	const tempPngPath = join(tmpdir(), `bat-cli-screenshot-${Date.now()}.png`);
	const browserPath = findSystemBrowser();

	try {
		if (browserPath) {
			console.log(`[bat-cli] Using system browser: ${browserPath}`);
			if (browserPath.toLowerCase().includes('firefox')) {
				execSync(
					`"${browserPath}" --headless --screenshot "${tempPngPath}" --window-size=1920,1080 "${target}"`,
					{ stdio: 'inherit' },
				);
			} else {
				// Chrome, Edge, Chromium
				execSync(
					`"${browserPath}" --headless --disable-gpu --screenshot="${tempPngPath}" --window-size=1920,1080 "${target}"`,
					{ stdio: 'inherit' },
				);
			}
		} else {
			console.log(`[bat-cli] System browser not found. Falling back to npx playwright...`);
			execSync(`npx playwright screenshot --viewport-size=1920,1080 "${target}" "${tempPngPath}"`, {
				stdio: 'inherit',
			});
		}

		if (!existsSync(tempPngPath)) {
			throw new Error('Screenshot file was not generated by browser headless command.');
		}

		console.log(`[bat-cli] Converting and compressing screenshot to WebP...`);
		const ok = await compressPngToWebp(tempPngPath, destWebpPath, 75);
		if (!ok) {
			throw new Error(
				'Failed to convert screenshot to WebP. Please ensure macOS `sips` is functional, or `python3` with `Pillow` is installed.',
			);
		}
		console.log(`[bat-cli] Screenshot successfully saved to ${destWebpPath}`);
	} finally {
		if (existsSync(tempPngPath)) {
			try {
				unlinkSync(tempPngPath);
			} catch {
				// ignore
			}
		}
	}
}
